<?php

namespace Database\Seeders;

use App\Models\AdTag;
use App\Models\Infrastructure;
use App\Models\Option;
use Google\Service\TagManager\Tag;
use Illuminate\Database\Seeder;

class OptionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $tags = [
            'uz' => [
                "Sun'iy o't",
                "Asfalt",
                "Kauchuklangan",
                "Parket",
                "O'rnatish",
                "o't",
                "Qum",
                "Tatami",
                "laminat",
                "Linoleum",
                "Gilam",
                "Qattiq",
                "Muz",
                "Teraflex",
                "Kurash gilami",
                "Budo mat",
                "kontrplak",
                "Sintetik çim",
                "Tennis",
                "Regupol",
                "Beton",
                "yopiq",
                'Ochiq',
                "gimnastika to'shaklari",
                "ko'ylak oldida",
                "ballboard",
                "to'rsiz darvoza",
                "to'rli darvoza",
                "darvozabon qo'lqoplari",
                "futbol to'plari",
                "voleybollar",
                "voleybol to'ri",
                "basketbollar",
                "tana nasoslari",
                "bodanlar",
                "gantellar",
                "ko'zgular",
                "yoga matlari",
                "Pilates to'plari",
                "fitness to'plari",
                "halqalar",
                "arqondan sakrash",
                "mashina",
                "qadam platformalari",
                "kengaytiruvchilar",
                "tennis to'plari",
                "tennis raketasi",
                "tennis to'ri",
                "boks qo'lqoplari",
                "bosma sumkasi",
                "sparring dummy",
                "devor yostig'i",
                "mashq panjalari",
                "shlemlar",
                'to\'rsiz xokkey goli',
                "xokkey to'ri",
                "tayoqlar",
                "figurali konkida uchish",
                "xokkey konkilari",
                "yuvgichlar",
                "nok",
                "pedalar",
                "makivara",
                "qo'lqoplar",
                "shin himoyasi",
                "kamarlar",
                "ko'ylaklar",
                "qalqonlar",
                "qo'ng'iroqlar",
                "arqon",
                "kichik to'siqlar",
                "qavat zinapoyalari",
                "konuslar",
                "pol nok",
                "chiplar",
                "bolalar darvozasi",
                'hushtaklar',
                'qog\'ozli doska',
                "stullar",
                "kattalar uchun qovoq raketalari",
                "bolalar uchun qovoqli raketkalar",
                "qovoq to'plari",
                'bosu',
                "yoga g'ishtlari",
                "yoga halqalari",
                "pnevmatik sumka",
                "Shved devori",
                "boks ringi",
                "raketalar",
                "chaqmoqlar",
                "to'r",
                "gilamlar",
                "yostiqlar",
                "yostiqlar",
            ],
            'ru' => [
                'Искусственная трава',
                'Асфальт',
                'Прорезиненное',
                'Паркет',
                'Грунт',
                'Трава',
                'Песок',
                'Татами',
                'Ламинат',
                'Линолеум',
                'Ковровое',
                'Хард',
                'Лёд',
                'Терафлекс',
                'Борцовский ковёр',
                'Будо мат',
                'Фaнера',
                'Синтетический газон',
                'Теннисит',
                'Регупол',
                'Бетонное',
                'Крытая',
                'Открытая',
                'гимнастические маты',
                'манишки',
                'табло',
                'ворота без сетки',
                'ворота с сеткой',
                'вратарские перчатки',
                'футбольные мячи',
                'волейбольные мячи',
                'волейбольная сетка',
                'баскетбольные мячи',
                'боди-пампы',
                'бодибары',
                'гантели',
                'зеркала',
                'коврики для йоги',
                'мячи для пилатеса',
                'мячи для фитнеса',
                'обручи',
                'скакалки',
                'станок',
                'степ-платформы',
                'эспандеры',
                'теннисные мячи',
                'теннисные ракетки',
                'теннисная сетка',
                'боксёрские перчатки',
                'боксёрский мешок',
                'спарринг-манекен',
                'настенная подушка',
                'тренировочные лапы',
                'шлемы',
                'ворота хоккейные без сетки',
                'ворота хоккейные с сеткой',
                'клюшки',
                'коньки фигурные',
                'коньки хоккейные',
                'шайбы',
                'груши',
                'пады',
                'макивары',
                'перчатки',
                'защита голени',
                'пояса',
                'жилеты',
                'щиты',
                'манекены',
                'канат',
                'малые барьеры',
                'напольные лестницы',
                'конусы',
                'напольная груша',
                'фишки',
                'детские ворота',
                'свистки',
                'флипчарт',
                'стулья',
                'взрослые ракетки для сквоша',
                'детские ракетки для сквоша',
                'мячи для сквоша',
                'босу',
                'кирпичи для йоги',
                'кольца для йоги',
                'пневмогруша',
                'шведская стенка',
                'ринг',
                'ракетки',
                'воланы',
                'сетка',
                'коврики',
                'подушки',
                'подушки',
            ],
            'en' => [
                'Artificial Grass',
                'Asphalt',
                'Rubberized',
                'Parquet',
                'Priming',
                'Grass',
                'Sand',
                'Tatami',
                'Laminate',
                'Linoleum',
                'Carpet',
                'Hard',
                'Ice',
                'Teraflex',
                'Wrestling carpet',
                'Budo mat',
                'Plywood',
                'Synthetic Turf',
                'Tennisit',
                'Regupol',
                'Concrete',
                'Covered',
                'Open',
                'gymnastic mats',
                'shirtfront',
                'scoreboard',
                'gate without mesh',
                'mesh gate',
                'goalkeeper `s gloves',
                'football balls',
                'volleyballs',
                'volleyball net',
                'basketballs',
                'body pumps',
                'bodybars',
                'dumbbells',
                'mirrors',
                'yoga mats',
                'Pilates balls',
                'fitness balls',
                'hoops',
                'jump rope',
                'machine',
                'step platforms',
                'expanders',
                'tennis balls',
                'tennis rocket',
                'tennis net',
                'boxing gloves',
                'punching bag',
                'sparring dummy',
                'wall pillow',
                'training paws',
                'helmets',
                'hockey goal without net',
                'hockey net',
                'sticks',
                'figure skates',
                'hockey skates',
                'washers',
                'pears',
                'pads',
                'makiwara',
                'gloves',
                'shin protection',
                'belts',
                'vests',
                'shields',
                'dummies',
                'rope',
                'small barriers',
                'floor stairs',
                'cones',
                'floor pear',
                'chips',
                'children\'s gate',
                'whistles',
                'flipchart',
                'chairs',
                'adult squash rackets',
                'children\'s squash rackets',
                'squash balls',
                'bosu',
                'yoga bricks',
                'yoga rings',
                'pneumatic bag',
                'Swedish wall',
                'boxing ring',
                'rackets',
                'flounces',
                'net',
                'rugs',
                'pillows',
                'pillows',
            ]
        ];
        foreach ($tags['uz'] as $key => $value) {
            AdTag::create([
                'title_uz' => ucfirst($value),
                'title_ru' => ucfirst($tags['ru'][$key]),
                'title_en' => ucfirst($tags['en'][$key]),
            ]);
        }
    }
}
